version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  lint:
    cmds:
      - golangci-lint run -c .golangci.yml
  test:
    cmds:
      - go test -timeout=60s -race -covermode=atomic -coverprofile=profile.cov ./...
  imports:
    cmds:
      - goimports -w .
  fumpt:
    cmds:
      - find . -name '*.go' -type f -exec gofumpt -w {} +
  clean:
    desc: Clean up
    cmds:
      - go mod tidy
      - task: fumpt
  update-deps:
    desc: Update dependencies
    cmds:
      - go get -u -d ./...