name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: 1.19
  LINT_VERSION: v1.50.x

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.LINT_VERSION }}

      - name: Test
        run: |
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...

      - name: Submit coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./unit.coverprofile
          flags: unittests-${{ runner.os }}
          slug: ${{ env.GITHUB_REPOSITORY }}